jobs:

  - name: push_image_tag1
    type: runSh
    steps:
      - IN: scriptami_repo
      - IN: scriptbase_repo
      - TASK:
        - script: IN/scriptami_repo/gitRepo/imagesPush/pushTags.sh 
        - script: IN/scriptami_repo/gitRepo/bldtest.sh      

  - name: push_image_tag1
    type: runSh
    steps:
     # - IN: ship_ver 
      - IN: scriptami_repo
      - TASK:
        - script: IN/scriptami_repo/gitRepo/bldtest.sh   
