jobs:
 
  - name: push_image_tag
    type: runSh
    steps:
      - IN: ship_ver #version resource hard coded current release version in the resource
        switch: off
      - IN: script_repo #gitrepo resource where we have to execute sh file
        switch: off
      - IN: ship_dh #
      - TASK:
        - script: IN/bldami_repo/gitRepo/imagesPush/pushTags.sh
    on_success:
      - script: echo 'succeeded'
    on_failure:
      - script: echo 'failed'
      
